/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 5;
  /** RegularExpression Id. */
  int LEITURA = 6;
  /** RegularExpression Id. */
  int SE = 7;
  /** RegularExpression Id. */
  int FIMSE = 8;
  /** RegularExpression Id. */
  int ENQUANTO = 9;
  /** RegularExpression Id. */
  int FIMENQUANTO = 10;
  /** RegularExpression Id. */
  int NUMERO = 11;
  /** RegularExpression Id. */
  int PALAVRA = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int AP = 14;
  /** RegularExpression Id. */
  int FP = 15;
  /** RegularExpression Id. */
  int PV = 16;
  /** RegularExpression Id. */
  int VIRGULA = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int VAR = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int NUM = 21;
  /** RegularExpression Id. */
  int SOMA = 22;
  /** RegularExpression Id. */
  int SUB = 23;
  /** RegularExpression Id. */
  int MUL = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int OU = 26;
  /** RegularExpression Id. */
  int ATRIB = 27;
  /** RegularExpression Id. */
  int IGUAL = 28;
  /** RegularExpression Id. */
  int CONCAT = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"exibe\"",
    "\"le\"",
    "\"se\"",
    "\"fim-se\"",
    "\"enquanto\"",
    "\"fim-enquanto\"",
    "\"numero\"",
    "\"palavra\"",
    "<CHAR>",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<STRING>",
    "<VAR>",
    "<DIGIT>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"OR\"",
    "\"<-\"",
    "\"=\"",
    "\"&\"",
  };

}
