/* Generated By:JavaCC: Do not edit this line. CompiladorConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 8;
  /** RegularExpression Id. */
  int LEITURA = 9;
  /** RegularExpression Id. */
  int SE = 10;
  /** RegularExpression Id. */
  int SENAO = 11;
  /** RegularExpression Id. */
  int FIMSE = 12;
  /** RegularExpression Id. */
  int ENQUANTO = 13;
  /** RegularExpression Id. */
  int FIMENQUANTO = 14;
  /** RegularExpression Id. */
  int PARA = 15;
  /** RegularExpression Id. */
  int FIMPARA = 16;
  /** RegularExpression Id. */
  int SELETOR = 17;
  /** RegularExpression Id. */
  int FIMSELETOR = 18;
  /** RegularExpression Id. */
  int CASO = 19;
  /** RegularExpression Id. */
  int FIMCASO = 20;
  /** RegularExpression Id. */
  int FACA = 21;
  /** RegularExpression Id. */
  int FAZERENQUANTO = 22;
  /** RegularExpression Id. */
  int REPETIR = 23;
  /** RegularExpression Id. */
  int ATE = 24;
  /** RegularExpression Id. */
  int NUMERO = 25;
  /** RegularExpression Id. */
  int PALAVRA = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int NUM = 28;
  /** RegularExpression Id. */
  int SOMA = 29;
  /** RegularExpression Id. */
  int SUB = 30;
  /** RegularExpression Id. */
  int MUL = 31;
  /** RegularExpression Id. */
  int DIV = 32;
  /** RegularExpression Id. */
  int POT = 33;
  /** RegularExpression Id. */
  int OU = 34;
  /** RegularExpression Id. */
  int E = 35;
  /** RegularExpression Id. */
  int ATRIB = 36;
  /** RegularExpression Id. */
  int IGUAL = 37;
  /** RegularExpression Id. */
  int CONCAT = 38;
  /** RegularExpression Id. */
  int MENOR = 39;
  /** RegularExpression Id. */
  int MAIORIGUAL = 40;
  /** RegularExpression Id. */
  int CHAR = 41;
  /** RegularExpression Id. */
  int AP = 42;
  /** RegularExpression Id. */
  int FP = 43;
  /** RegularExpression Id. */
  int AC = 44;
  /** RegularExpression Id. */
  int FC = 45;
  /** RegularExpression Id. */
  int PV = 46;
  /** RegularExpression Id. */
  int DP = 47;
  /** RegularExpression Id. */
  int VIRGULA = 48;
  /** RegularExpression Id. */
  int STRING = 49;
  /** RegularExpression Id. */
  int VAR = 50;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentarioGeral = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"exibe\"",
    "\"le\"",
    "\"se\"",
    "\"senao\"",
    "\"fim-se\"",
    "\"enquanto\"",
    "\"fim-enquanto\"",
    "\"para\"",
    "\"fim-para\"",
    "\"seletor\"",
    "\"fim-seletor\"",
    "\"caso\"",
    "\"fim-caso\"",
    "\"faca\"",
    "\"fazer-enquanto\"",
    "\"repetir\"",
    "\"ate\"",
    "\"numero\"",
    "\"palavra\"",
    "<DIGIT>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"OU\"",
    "\"E\"",
    "\"<-\"",
    "\"=\"",
    "\"&\"",
    "\"<\"",
    "\">=\"",
    "<CHAR>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "<STRING>",
    "<VAR>",
  };

}
